default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: db   # ← Docker の PostgreSQL コンテナ名

development:
  <<: *default
  database: tsumugi_development

test:
  <<: *default
  database: tsumugi_test

production:
  <<: *default
  database: tsumugi_production
  username: tsumugi
  password: <%= ENV["TSUMUGI_DATABASE_PASSWORD"] %>
