test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# 開発環境ではローカルストレージを使用
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# 本番環境ではAmazon S3を使用
amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  bucket: <%= ENV['AWS_S3_BUCKET'] %>
